/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Brakes.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Brakes(props) {
  const { nodes, materials } = useGLTF('/Brakes.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['visse.002']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Chrome_Text_Logo} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['plaquette_de_frein.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Brakes.gltf')

export default Brakes