/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/MainTires.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import MainTires from "./MainTires";

const PrioraTires = ({ params }) => {
  return (
    <>
      {params.map((wheel) => (
        <MainTires
          key={wheel.id}
          scale={wheel.scale}
          position={wheel.position}
        />
      ))}
    </>
  );
};

export default PrioraTires;
