/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/lamp.glb
Author: Zian (https://sketchfab.com/zian_0912)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lamp-bdf4f1abce7b4440a8a520d568f9ea34
Title: Lamp
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Lamp(props) {
  const { nodes, materials } = useGLTF('/lamp.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Lamp_01a001__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/lamp.glb')
export default Lamp